version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - mkdir package

      - |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt -t package
        fi

  build:
    commands:
      - echo Validating Lambda code...
      - python -m py_compile lambda.py

      - echo Copying Lambda source...
      - cp lambda.py package/

      - echo Creating deployment package...
      - cd package
      - zip -r ../lambda.zip .

artifacts:
  files:
    - lambda.zip