version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip

      - |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt -t .
        fi

  build:
    commands:
      - python -m py_compile lambda.py

artifacts:
  files:
    - '**/*'
  discard-paths: no